#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: ErgPower

# Name of the author
author: Adrian Edwards

# Short bio or description (displayed in the header)
description: Green energy one meter at a time 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/logo/ErgPower.svg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: MoralCode/ErgPower
  instagram:
  linkedin: 
  pinterest:
  rss: true
  twitter: 
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://moralcode.github.io/ErgPower/
enforce_ssl: https://moralcode.github.io/ErgPower/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/ErgPower"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /log/:year-:month-:day-:title:output_ext

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "default"